resources:
  - url: http://127.0.0.1:5000/magic-card.js
    type: module
views:
  - cards:
      - type: custom:magic-card
        name: magic Card Development
        entity: sun.sun
        test_gui: true
